# Linnaeus Loadbalancer / reverse proxy
#
#
#
#
#
class role_linnaeusng::lb (


# cert_array makes use of letsencryptssl::installcert class
  $cert_array                   = ['linnaeus.naturalis.nl','identify.naturalis.nl','orchids.naturalis.nl','determineren.nederlandsesoorten.nl','dutchcaribbeanspecies.org','nederlandsesoorten.nl','www.dierenzoeker.nl','www.grasshoppersofeurope.com','heukels.naturalis.nl'],
  Hash $server       = { 'default_server'            => { 'proxy' => 'http://default_server',
                                                    'server_name'  => ['_'],
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                    'location_cfg_append' => { 'rewrite' => '^ http://linnaeus.naturalis.nl permanent'},
                                                   },
                   'nederlandsesoorten_alt'    => { 'proxy' => 'http://nsr-frontend',
                                                    'server_name'  => ['soortenregister.nl','www.soortenregister.nl','nederlandsesoorten.nl'],
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/nederlandsesoorten.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/nederlandsesoorten.nl/privkey.pem',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://www.nederlandsesoorten.nl$request_uri permanent'},
                                                   },
                   'nederlandsesoorten_server'  => { 'proxy' => 'http://nsr-frontend',
                                                    'server_name'  => ['www.nederlandsesoorten.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/nederlandsesoorten.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/nederlandsesoorten.nl/privkey.pem',
                                                   },
                   'dutchcaribbeanspecies_server' => { 'proxy' => 'http://dcs-frontend',
                                                    'server_name'  => ['www.dutchcaribbeanspecies.org','dutchcaribbeanspecies.org'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/dutchcaribbeanspecies.org/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/dutchcaribbeanspecies.org/privkey.pem',
                                                   },
                   'various-001_server'         => { 'proxy' => 'http://various-001',
                                                    'server_name'  => ['various-001.linnaeus.naturalis.nl','aetideidae.linnaeus.naturalis.nl','agromyzidae.linnaeus.naturalis.nl','bats-india.linnaeus.naturalis.nl','bris.linnaeus.naturalis.nl','birds-europe.linnaeus.naturalis.nl','blackflies.linnaeus.naturalis.nl','braconidae.linnaeus.naturalis.nl','butterflies-europe.linnaeus.naturalis.nl','chironomidae-exuviae.linnaeus.naturalis.nl','chironomidae-larvae.linnaeus.naturalis.nl','crabs-japan.linnaeus.naturalis.nl','dagvlinders-europa.linnaeus.naturalis.nl','davalliacea.linnaeus.naturalis.nl','duikgids.linnaeus.naturalis.nl','paddenstoelen.linnaeus.naturalis.nl','decapodos-chile.linnaeus.naturalis.nl','diaspididae.linnaeus.naturalis.nl','eurasian-tortricidae.linnaeus.naturalis.nl','european-limnofauna.linnaeus.naturalis.nl','fish-eggs-and-larvae-from-amw.linnaeus.naturalis.nl','fishes-fnam.linnaeus.naturalis.nl','flora-arborea-chile.linnaeus.naturalis.nl','caesalpinioideae.linnaeus.naturalis.nl','flora-burren.linnaeus.naturalis.nl','fw-oligochaeta.linnaeus.naturalis.nl','dinoflagellates.linnaeus.naturalis.nl','insecten-europa.linnaeus.naturalis.nl','flora-british-isles.linnaeus.naturalis.nl','caribbean-diving.linnaeus.naturalis.nl','mushrooms.linnaeus.naturalis.nl','lemurs.linnaeus.naturalis.nl','libellenlarven.linnaeus.naturalis.nl','ns-anthozoa.linnaeus.naturalis.nl','ns-brachiopoda.linnaeus.naturalis.nl','ns-crustacea.linnaeus.naturalis.nl','ns-echinodermata.linnaeus.naturalis.nl','ns-miscellaneous-worms.linnaeus.naturalis.nl','ns-mollusca.linnaeus.naturalis.nl','ns-nemertina.linnaeus.naturalis.nl','ns-platyhelminthes.linnaeus.naturalis.nl','ns-polychaeta.linnaeus.naturalis.nl','ns-pycnogonida.linnaeus.naturalis.nl','ns-sipuncula.linnaeus.naturalis.nl','ns-tunicata.linnaeus.naturalis.nl','marine-lobsters.linnaeus.naturalis.nl','marine-mammals.linnaeus.naturalis.nl','marine-planarians.linnaeus.naturalis.nl','marine-ostracods.linnaeus.naturalis.nl','mormyridae.linnaeus.naturalis.nl','sea-cucumbers.linnaeus.naturalis.nl','orchids-philippines.linnaeus.naturalis.nl','otoliths-northsea.linnaeus.naturalis.nl','pelagic-molluscs.linnaeus.naturalis.nl','prosea-bamboos.linnaeus.naturalis.nl','prosea-edible-fruits-and-nuts.linnaeus.naturalis.nl','prosea-rattans.linnaeus.naturalis.nl','prosea-timber-trees.linnaeus.naturalis.nl','indo-malayan-reef-corals.linnaeus.naturalis.nl','reptielen-en-amfibieen.linnaeus.naturalis.nl','reptiles-and-amphibians.linnaeus.naturalis.nl','sharks.linnaeus.naturalis.nl','sponges-ne-atlantic.linnaeus.naturalis.nl','turbellaria.linnaeus.naturalis.nl','turtles.linnaeus.naturalis.nl','genitalia-preparation.linnaeus.naturalis.nl','useful-plants.linnaeus.naturalis.nl','vogels-europa.linnaeus.naturalis.nl','zoetwatervissen.linnaeus.naturalis.nl','ns-zooplankton.linnaeus.naturalis.nl','sat-zooplankton.linnaeus.naturalis.nl','legacy.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-002_server'         => { 'proxy' => 'http://various-002',
                                                    'server_name'  => ['various-002.linnaeus.naturalis.nl','floranl.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-003_server'         => { 'proxy' => 'http://various-003',
                                                    'server_name' => ['various-003.linnaeus.naturalis.nl','img-classify.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-005_server'         => { 'proxy' => 'http://various-005',
                                                    'server_name' => ['various-005.linnaeus.naturalis.nl','doignies.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-006_server'         => { 'proxy' => 'http://various-006',
                                                    'server_name' => ['various-006.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-007_server'         => { 'proxy' => 'http://various-007',
                                                    'server_name' => ['various-007.linnaeus.naturalis.nl','glomera.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-008_server'         => { 'proxy' => 'http://various-008',
                                                    'server_name' => ['various-008.linnaeus.naturalis.nl','flora-central-africa.linnaeus.naturalis.nl','grasses-cameroon.linnaeus.naturalis.nl','grasses-africa.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-010_server'         => { 'proxy' => 'http://various-010',
                                                    'server_name' => ['various-010.linnaeus.naturalis.nl','torymus.linnaeus.naturalis.nl','pteromalus.linnaeus.naturalis.nl','tetrastichinae.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-011_server'         => { 'proxy' => 'http://various-011',
                                                    'server_name' => ['various-011.linnaeus.naturalis.nl','bseai.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'identify_server'            => { 'proxy' => 'http://various-011',
                                                    'server_name' => ['identify.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/identify.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/identify.naturalis.nl/privkey.pem',
                                                   },
                   'various-012_server'         => { 'proxy' => 'http://various-012',
                                                    'server_name' => ['various-012.linnaeus.naturalis.nl','orchidsnguinea.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-014_server'         => { 'proxy' => 'http://various-014',
                                                    'server_name' => ['various-014.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'grasshoppers_alt'          => { 'proxy' => 'http://grasshoppers-frontend',
                                                    'server_name'  => ['www.ortheur.org','ortheur.org','grasshoppersofeurope.com'],
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/www.grasshoppersofeurope.com/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/www.grasshoppersofeurope.com/privkey.pem',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://www.grasshoppersofeurope.com$request_uri permanent'},
                                                   },
                   'grasshoppers_server'        => { 'proxy' => 'http://grasshoppers-frontend',
                                                    'server_name'  => ['www.grasshoppersofeurope.com'],
                                                    'ssl_redirect' => true,
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/www.grasshoppersofeurope.com/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/www.grasshoppersofeurope.com/privkey.pem',
                                                   },
                   'orchidsnguinea_server'      => { 'proxy' => 'http://various-012',
                                                    'server_name' => ['orchids.naturalis.nl','www.orchids.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/orchids.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/orchids.naturalis.nl/privkey.pem',
                                                   },
                   'various-016_server'         => { 'proxy' => 'http://various-016',
                                                    'server_name' => ['various-016.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'heukels_server'             => { 'proxy' => 'http://various-016',
                                                    'server_name' => ['heukels.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/heukels.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/heukels.naturalis.nl/privkey.pem',
                                                   },
                   'various-017_server'         => { 'proxy' => 'http://various-017',
                                                    'server_name' => ['various-017.linnaeus.naturalis.nl','flore-de-la-belgique.linnaeus.naturalis.nl','flora-van-belgie.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-018_server'         => { 'proxy' => 'http://various-018',
                                                    'server_name' => ['various-018.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-019_server'         => { 'proxy' => 'http://various-019',
                                                    'server_name' => ['various-019.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-020_server'         => { 'proxy' => 'http://various-020',
                                                    'server_name' => ['various-020.linnaeus.naturalis.nl','catpalhet.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-021_server'         => { 'proxy' => 'http://various-021',
                                                    'server_name' => ['various-021.linnaeus.naturalis.nl','worldferns.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-022_server'         => { 'proxy' => 'http://various-022',
                                                    'server_name' => ['various-022.linnaeus.naturalis.nl','ttik.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-023_server'         => { 'proxy' => 'http://various-023',
                                                    'server_name' => ['various-023.linnaeus.naturalis.nl','idredsea.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-024_server'         => { 'proxy' => 'http://various-024',
                                                    'server_name' => ['various-024.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-025_server'         => { 'proxy' => 'http://various-025',
                                                    'server_name' => ['various-025.linnaeus.naturalis.nl','lithocolletinae.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-026_server'         => { 'proxy' => 'http://various-026',
                                                    'server_name' => ['various-026.linnaeus.naturalis.nl','hermannceylon.linnaeus.naturalis.nl','triphoroidea.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-027_server'         => { 'proxy' => 'http://various-027',
                                                    'server_name' => ['various-027.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-028_server'         => { 'proxy' => 'http://various-028',
                                                    'server_name' => ['various-028.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-029_server'         => { 'proxy' => 'http://various-029',
                                                    'server_name' => ['various-029.linnaeus.naturalis.nl','cetaceanscapulae.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-030_server'         => { 'proxy' => 'http://various-030',
                                                    'server_name' => ['various-030.linnaeus.naturalis.nl','viva.linnaeus.naturalis.nl'],
                                                    'ssl'         => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-031_server'         => { 'proxy' => 'http://various-031',
                                                    'server_name' => ['various-031.linnaeus.naturalis.nl','ectoedemia.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-032_server'         => { 'proxy' => 'http://various-032',
                                                    'server_name' => ['various-032.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'dierenzoeker'               => { 'proxy' => 'http://various-032',
                                                    'server_name'  => ['www.dierenzoeker.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/www.dierenzoeker.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/www.dierenzoeker.nl/privkey.pem',
                                                   },
                   'dierenzoeker_alt'           => { 'proxy' => 'http://various-032',
                                                    'server_name'  => ['dierenzoeker.nl','www.dierezoeker.nl','dierezoeker.nl'],
                                                    'ssl'          => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/www.dierenzoeker.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/www.dierenzoeker.nl/privkey.pem',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://www.dierenzoeker.nl$request_uri permanent'},
                                                   },
                   'various-033_server'         => { 'proxy' => 'http://various-033',
                                                    'server_name' => ['various-033.linnaeus.naturalis.nl','plantgenera.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-034_server'         => { 'proxy' => 'http://various-034',
                                                    'server_name' => ['various-034.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-035_server'         => { 'proxy' => 'http://various-035',
                                                    'server_name' => ['various-035.linnaeus.naturalis.nl','oggngbotany.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-036_server'         => { 'proxy' => 'http://various-036',
                                                    'server_name' => ['various-036.linnaeus.naturalis.nl','SEAsianfloweringplants.linnaeus.naturalis.nl'],
                                                    'ssl_redirect' => true,
                                                    'ssl'         => true,
                                                    'ssl_cert'    => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-037_server'         => { 'proxy' => 'http://various-037',
                                                    'server_name'  => ['various-037.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-038_server'         => { 'proxy' => 'http://various-038',
                                                    'server_name'  => ['various-038.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-039_server'         => { 'proxy' => 'http://various-039',
                                                    'server_name'  => ['various-039.linnaeus.naturalis.nl','euphausiids.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'determineren_server'        => { 'proxy' => 'http://various-040',
                                                    'server_name'  => ['determineren.nederlandsesoorten.nl','determinatie.nederlandsesoorten.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/determineren.nederlandsesoorten.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/determineren.nederlandsesoorten.nl/privkey.pem',
                                                   },
                   'various-040_server'         => { 'proxy' => 'http://various-040',
                                                    'server_name'  => ['various-040.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-041_server'         => { 'proxy' => 'http://various-041',
                                                    'server_name'  => ['various-041.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-042_server'         => { 'proxy' => 'http://various-042',
                                                    'server_name'  => ['various-042.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-043_server'         => { 'proxy' => 'http://various-043',
                                                    'server_name'  => ['various-043.linnaeus.naturalis.nl','uitgebloeide-orchideeen.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-044_server'         => { 'proxy' => 'http://various-044',
                                                    'server_name'  => ['various-044.linnaeus.naturalis.nl','educatie.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-045_server'         => { 'proxy' => 'http://various-045',
                                                    'server_name'  => ['various-045.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-054_server'         => { 'proxy' => 'http://various-054',
                                                    'server_name'  => ['various-054.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-055_server'         => { 'proxy' => 'http://various-055',
                                                    'server_name'  => ['various-055.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                   'various-070_server'         => { 'proxy' => 'http://various-070',
                                                    'server_name'  => ['various-070.linnaeus.naturalis.nl'],
                                                    'ssl'          => true,
                                                    'ssl_redirect' => true,
                                                    'ssl_cert'     => '/etc/letsencrypt/live/linnaeus.naturalis.nl/fullchain.pem',
                                                    'ssl_key'      => '/etc/letsencrypt/live/linnaeus.naturalis.nl/privkey.pem',
                                                   },
                 },
  Hash $location    = {'loc_various-003_ssl'       => { 'location' => '/linnaeus_ng/admin/',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://$host$request_uri? permanent' },
                                                    'server' => 'various-003_server',
                                                    'proxy' => 'https://various-003'},
                   'loc_various-005_ssl'       => { 'location' => '/linnaeus_ng/admin/',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://$host$request_uri? permanent' },
                                                    'server' => 'various-005_server',
                                                    'proxy' => 'https://various-005'},
                   'loc_various-006_ssl'       => { 'location' => '/linnaeus_ng/admin/',
                                                    'location_cfg_append' => { 'rewrite' => '^ https://$host$request_uri? permanent' },
                                                    'server' => 'various-006_server',
                                                    'proxy' => 'https://various-006'},
                     },
  Hash $upstream    = { 'various-001'               => { 'members' => ['172.16.1.160'] },
                   'various-002'               => { 'members' => ['172.16.1.167'] },
                   'various-003'               => { 'members' => ['172.16.1.55'] },
                   'various-005'               => { 'members' => ['172.16.1.57'] },
                   'various-006'               => { 'members' => ['172.16.1.58'] },
                   'various-007'               => { 'members' => ['172.16.1.175'] },
                   'various-008'               => { 'members' => ['172.16.1.176'] },
                   'various-010'               => { 'members' => ['172.16.1.162'] },
                   'various-011'               => { 'members' => ['172.16.1.164'] },
                   'various-012'               => { 'members' => ['172.16.1.165'] },
                   'various-014'               => { 'members' => ['172.16.1.186'] },
                   'various-016'               => { 'members' => ['172.16.1.166'] },
                   'various-017'               => { 'members' => ['172.16.1.168'] },
                   'various-018'               => { 'members' => ['172.16.1.169'] },
                   'various-019'               => { 'members' => ['172.16.1.187'] },
                   'various-020'               => { 'members' => ['172.16.1.179'] },
                   'various-021'               => { 'members' => ['172.16.1.170'] },
                   'various-022'               => { 'members' => ['172.16.1.188'] },
                   'various-023'               => { 'members' => ['172.16.1.189'] },
                   'various-024'               => { 'members' => ['172.16.1.190'] },
                   'various-025'               => { 'members' => ['172.16.1.181'] },
                   'various-026'               => { 'members' => ['172.16.1.182'] },
                   'various-027'               => { 'members' => ['172.16.1.96'] },
                   'various-028'               => { 'members' => ['172.16.1.191'] },
                   'various-029'               => { 'members' => ['172.16.1.183'] },
                   'various-030'               => { 'members' => ['172.16.1.192'] },
                   'various-031'               => { 'members' => ['172.16.1.193'] },
                   'various-032'               => { 'members' => ['172.16.1.185'] },
                   'various-033'               => { 'members' => ['172.16.1.171'] },
                   'various-034'               => { 'members' => ['172.16.1.194'] },
                   'various-035'               => { 'members' => ['172.16.1.172'] },
                   'various-036'               => { 'members' => ['172.16.1.184'] },
                   'various-037'               => { 'members' => ['172.16.1.157'] },
                   'various-038'               => { 'members' => ['172.16.1.158'] },
                   'various-039'               => { 'members' => ['172.16.1.159'] },
                   'various-040'               => { 'members' => ['172.16.1.155'] },
                   'various-041'               => { 'members' => ['172.16.1.205'] },
                   'various-042'               => { 'members' => ['172.16.1.206'] },
                   'various-043'               => { 'members' => ['172.16.1.207'] },
                   'various-044'               => { 'members' => ['172.16.1.208'] },
                   'various-045'               => { 'members' => ['172.16.1.209'] },
                   'various-054'               => { 'members' => ['172.16.1.177'] },
                   'various-055'               => { 'members' => ['172.16.1.178'] },
                   'various-070'               => { 'members' => ['172.16.1.195'] },
                   'nsr-frontend'              => { 'members' => ['172.16.1.89'] },
                   'dcs-frontend'              => { 'members' => ['172.16.1.128'] },
                   'grasshoppers-frontend'     => { 'members' => ['145.136.243.126'] },
                   'default_server'            => { 'members' => ['145.136.241.149'] },
                 },

){

  class { 'letsencryptssl::installcert':
    cert_array             => $cert_array,
    cert_webservice        => 'nginx',
  }


  class { 'nginx':
    names_hash_bucket_size  => '512',
    client_max_body_size    => '100M',
    keepalive_timeout       => '600s',
    proxy_send_timeout      => '600s',
    proxy_read_timeout      => '600s',
    proxy_connect_timeout   => '600',
  }

#  create_resources
  create_resources(nginx::resource::server,$server,{})
  create_resources(nginx::resource::location,$location,{})
  create_resources(nginx::resource::upstream,$upstream,{})
}

